"""Initial schema: identity, profile and weight logs (Phase 1).

Hand-written rather than autogenerated. Autogenerate is a draft — it does not emit the
extensions, the updated_at trigger, or the partial indexes that carry the correctness
guarantees in docs/03.

Revision ID: 0001_initial
Revises:
Created: 2026-07-29
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---------------------------------------------------------------- extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')

    # updated_at is maintained by a trigger as well as by the ORM, so a bulk UPDATE or a
    # manual fix in psql cannot leave a stale timestamp behind.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ---------------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.String(20), server_default="user", nullable=False),
        sa.Column("status", sa.String(20), server_default="pending", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(64), server_default="UTC", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('user','moderator','admin')", name="ck_users_role_valid"),
        sa.CheckConstraint(
            "status IN ('pending','active','suspended','deleted')", name="ck_users_status_valid"
        ),
        sa.CheckConstraint("length(email) BETWEEN 3 AND 320", name="ck_users_email_len"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    # Partial unique: a hard-deleted user's address becomes reusable, live ones cannot collide.
    op.create_index(
        "uq_users_email_active", "users", ["email"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index("ix_users_status", "users", ["status"], postgresql_where=sa.text("deleted_at IS NULL"))

    # -------------------------------------------------------------- user_devices
    op.create_table(
        "user_devices",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("platform", sa.String(20), nullable=False),
        sa.Column("device_name", sa.String(120), nullable=True),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("platform IN ('ios','android','web')", name="ck_user_devices_platform_valid"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_devices_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_user_devices"),
    )
    op.create_index("ix_user_devices_user", "user_devices", ["user_id"])

    # ------------------------------------------------------------ auth_identities
    op.create_table(
        "auth_identities",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(20), nullable=False),
        sa.Column("provider_subject", sa.String(255), nullable=False),
        sa.Column("provider_email", postgresql.CITEXT(), nullable=True),
        sa.Column("raw_profile", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("provider IN ('google','apple')", name="ck_auth_identities_provider_valid"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_auth_identities_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_auth_identities"),
        # Stops one provider account from claiming two CoreSync accounts.
        sa.UniqueConstraint("provider", "provider_subject", name="uq_auth_identity"),
    )
    op.create_index("ix_auth_identities_user", "auth_identities", ["user_id"])

    # ------------------------------------------------------------- refresh_tokens
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(32), nullable=False),
        sa.Column("device_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("replaced_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(50), nullable=True),
        sa.Column("created_ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_refresh_tokens_user_id_users", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["device_id"], ["user_devices.id"], name="fk_refresh_tokens_device_id_user_devices", ondelete="SET NULL"
        ),
        # Self-referencing rotation chain; SET NULL so revoking never orphans a row.
        sa.ForeignKeyConstraint(
            ["replaced_by"], ["refresh_tokens.id"], name="fk_refresh_tokens_replaced_by_refresh_tokens", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id"], postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.create_index("ix_refresh_tokens_replaced_by", "refresh_tokens", ["replaced_by"])

    # ----------------------------------------------------------- single_use_tokens
    op.create_table(
        "single_use_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("purpose", sa.String(30), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('email_verification','password_reset')", name="ck_single_use_tokens_purpose_valid"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_single_use_tokens_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_single_use_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_single_use_tokens_token_hash"),
    )
    op.create_index(
        "ix_single_use_tokens_user_purpose",
        "single_use_tokens",
        ["user_id", "purpose"],
        postgresql_where=sa.text("used_at IS NULL"),
    )

    # --------------------------------------------------------------- user_settings
    op.create_table(
        "user_settings",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("unit_system", sa.String(10), server_default="metric", nullable=False),
        sa.Column("theme", sa.String(10), server_default="system", nullable=False),
        sa.Column("language", sa.String(10), server_default="en", nullable=False),
        sa.Column("profile_visibility", sa.String(20), server_default="private", nullable=False),
        # AI training opt-in defaults to false and stays false unless the user acts.
        sa.Column("ai_training_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("marketing_email_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("unit_system IN ('metric','imperial')", name="ck_user_settings_unit_system_valid"),
        sa.CheckConstraint("theme IN ('system','light','dark')", name="ck_user_settings_theme_valid"),
        sa.CheckConstraint(
            "profile_visibility IN ('private','followers','public')", name="ck_user_settings_profile_visibility_valid"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_settings_user_id_users", ondelete="CASCADE"),
        # The PK is the FK, which enforces the 0..1 relationship at schema level.
        sa.PrimaryKeyConstraint("user_id", name="pk_user_settings"),
    )

    # --------------------------------------------------------------- user_profiles
    op.create_table(
        "user_profiles",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("display_name", sa.String(80), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(20), nullable=True),
        sa.Column("height_cm", sa.Numeric(6, 2), nullable=True),
        sa.Column("activity_level", sa.String(20), server_default="moderate", nullable=False),
        sa.Column("experience_level", sa.String(20), server_default="beginner", nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        # 13 is the registration floor. Enforced here so no code path can create a
        # younger account, whatever the API layer does.
        sa.CheckConstraint(
            "date_of_birth IS NULL OR (date_of_birth > DATE '1900-01-01' "
            "AND date_of_birth < (CURRENT_DATE - INTERVAL '13 years'))",
            name="ck_user_profiles_dob_valid",
        ),
        sa.CheckConstraint(
            "gender IS NULL OR gender IN ('male','female','other','prefer_not_to_say')",
            name="ck_user_profiles_gender_valid",
        ),
        sa.CheckConstraint(
            "activity_level IN ('sedentary','light','moderate','active','very_active')",
            name="ck_user_profiles_activity_level_valid",
        ),
        sa.CheckConstraint(
            "experience_level IN ('beginner','intermediate','advanced')",
            name="ck_user_profiles_experience_level_valid",
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR (height_cm > 0 AND height_cm <= 300)", name="ck_user_profiles_height_range"
        ),
        sa.CheckConstraint("bio IS NULL OR length(bio) <= 500", name="ck_user_profiles_bio_len"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_profiles_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name="pk_user_profiles"),
    )

    # ------------------------------------------------------------------ user_goals
    op.create_table(
        "user_goals",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("goal_type", sa.String(20), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(6, 2), nullable=True),
        sa.Column("weekly_rate_kg", sa.Numeric(4, 3), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("ended_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "goal_type IN ('lose_fat','maintain','gain_muscle','recomp','performance')",
            name="ck_user_goals_goal_type_valid",
        ),
        sa.CheckConstraint("ended_on IS NULL OR ended_on >= started_on", name="ck_user_goals_goal_range"),
        sa.CheckConstraint(
            "target_weight_kg IS NULL OR (target_weight_kg > 20 AND target_weight_kg <= 500)",
            name="ck_user_goals_target_weight_range",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_goals_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_user_goals"),
    )
    # Exactly one open goal per user.
    op.create_index(
        "uq_user_goals_current", "user_goals", ["user_id"], unique=True, postgresql_where=sa.text("ended_on IS NULL")
    )
    op.create_index("ix_user_goals_user", "user_goals", ["user_id", "started_on"])

    # ----------------------------------------------------------- nutrition_targets
    op.create_table(
        "nutrition_targets",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("calories", sa.Numeric(8, 2), nullable=False),
        sa.Column("protein_g", sa.Numeric(9, 3), nullable=False),
        sa.Column("carbs_g", sa.Numeric(9, 3), nullable=False),
        sa.Column("fat_g", sa.Numeric(9, 3), nullable=False),
        sa.Column("fiber_g", sa.Numeric(9, 3), nullable=True),
        sa.Column("water_ml", sa.Numeric(9, 2), server_default="2500", nullable=False),
        sa.Column("source", sa.String(10), server_default="auto", nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("source IN ('auto','manual','ai')", name="ck_nutrition_targets_source_valid"),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from", name="ck_nutrition_targets_targets_range"
        ),
        # THE SAFETY FLOOR. Prompt instructions and service validation can both be
        # bypassed by a bug; this cannot. No code path — including the AI coach — can
        # write a dangerous calorie target. See docs/10 §7.1.
        sa.CheckConstraint("calories >= 1000", name="ck_nutrition_targets_calorie_floor"),
        sa.CheckConstraint("calories <= 10000", name="ck_nutrition_targets_calorie_ceiling"),
        sa.CheckConstraint(
            "protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0", name="ck_nutrition_targets_macros_positive"
        ),
        sa.CheckConstraint("water_ml >= 0 AND water_ml <= 10000", name="ck_nutrition_targets_water_range"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_nutrition_targets_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_nutrition_targets"),
    )
    # Exactly one open-ended (current) target row per user.
    op.create_index(
        "uq_nutrition_targets_current",
        "nutrition_targets",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_index("ix_nutrition_targets_user_from", "nutrition_targets", ["user_id", "effective_from"])

    # ---------------------------------------------------------------- weight_logs
    op.create_table(
        "weight_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(6, 2), nullable=False),
        sa.Column("body_fat_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("measurement_context", sa.String(20), server_default="unspecified", nullable=False),
        sa.Column("trend_weight_kg", sa.Numeric(6, 2), nullable=True),
        sa.Column("source", sa.String(20), server_default="manual", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("weight_kg > 0 AND weight_kg <= 1000", name="ck_weight_logs_weight_range"),
        sa.CheckConstraint(
            "body_fat_pct IS NULL OR (body_fat_pct >= 0 AND body_fat_pct <= 100)",
            name="ck_weight_logs_body_fat_range",
        ),
        sa.CheckConstraint(
            "measurement_context IN ('morning_fasted','morning','evening','post_workout','unspecified')",
            name="ck_weight_logs_context_valid",
        ),
        sa.CheckConstraint(
            "source IN ('manual','healthkit','google_fit','smart_scale','onboarding')",
            name="ck_weight_logs_source_valid",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_weight_logs_user_id_users", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_weight_logs"),
        # One weigh-in per day: multiple daily weights are noise and corrupt the trend.
        sa.UniqueConstraint("user_id", "local_date", name="uq_weight_per_day"),
    )
    op.create_index("ix_weight_logs_user_date", "weight_logs", ["user_id", "local_date"])

    # --------------------------------------------------------------- updated_at triggers
    for table in (
        "users",
        "user_devices",
        "user_settings",
        "user_profiles",
        "user_goals",
        "nutrition_targets",
        "weight_logs",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
            """
        )


def downgrade() -> None:
    for table in (
        "users",
        "user_devices",
        "user_settings",
        "user_profiles",
        "user_goals",
        "nutrition_targets",
        "weight_logs",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")

    op.drop_table("weight_logs")
    op.drop_table("nutrition_targets")
    op.drop_table("user_goals")
    op.drop_table("user_profiles")
    op.drop_table("user_settings")
    op.drop_table("single_use_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("auth_identities")
    op.drop_table("user_devices")
    op.drop_table("users")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # Extensions are deliberately left in place: other databases in the cluster may use
    # them, and dropping an extension is not reversible in any useful sense.
