"""The curated exercise catalog.

One row per movement, in a deliberately compact tuple form so the whole library stays
reviewable in a diff. Adding an exercise is one line; the seeder derives its id from the
slug, so a new row is additive and re-running is idempotent.

Column order:
    slug, name, category, force, mechanic, difficulty, logging_type, unilateral,
    primary muscles, secondary muscles, equipment

Empty strings mean "not applicable" (a plank has no force type) or "use the default"
(``logging_type`` defaults to ``weight_reps``). Muscle and equipment columns are
pipe-separated slugs from ``reference.py``; the seeder fails loudly on an unknown slug
rather than silently writing an exercise nobody can filter for.
"""

from __future__ import annotations

ExerciseRow = tuple[str, str, str, str, str, str, str, bool, str, str, str]

# fmt: off
EXERCISES: tuple[ExerciseRow, ...] = (
    # ------------------------------------------------------------------- chest
    ("barbell-bench-press", "Barbell Bench Press", "strength", "push", "compound", "intermediate", "", False, "mid_chest", "triceps|front_delts", "barbell|bench"),
    ("incline-barbell-bench-press", "Incline Barbell Bench Press", "strength", "push", "compound", "intermediate", "", False, "upper_chest", "triceps|front_delts", "barbell|incline_bench"),
    ("decline-barbell-bench-press", "Decline Barbell Bench Press", "strength", "push", "compound", "intermediate", "", False, "lower_chest", "triceps|front_delts", "barbell|bench"),
    ("close-grip-bench-press", "Close-Grip Bench Press", "strength", "push", "compound", "intermediate", "", False, "triceps|mid_chest", "front_delts", "barbell|bench"),
    ("dumbbell-bench-press", "Dumbbell Bench Press", "strength", "push", "compound", "beginner", "", False, "mid_chest", "triceps|front_delts", "dumbbell|bench"),
    ("incline-dumbbell-press", "Incline Dumbbell Press", "strength", "push", "compound", "beginner", "", False, "upper_chest", "triceps|front_delts", "dumbbell|incline_bench"),
    ("decline-dumbbell-press", "Decline Dumbbell Press", "strength", "push", "compound", "intermediate", "", False, "lower_chest", "triceps", "dumbbell|bench"),
    ("dumbbell-fly", "Dumbbell Fly", "strength", "push", "isolation", "beginner", "", False, "mid_chest", "front_delts", "dumbbell|bench"),
    ("incline-dumbbell-fly", "Incline Dumbbell Fly", "strength", "push", "isolation", "beginner", "", False, "upper_chest", "front_delts", "dumbbell|incline_bench"),
    ("cable-fly", "Cable Fly", "strength", "push", "isolation", "beginner", "", False, "mid_chest", "front_delts", "cable"),
    ("low-to-high-cable-fly", "Low-to-High Cable Fly", "strength", "push", "isolation", "beginner", "", False, "upper_chest", "front_delts", "cable"),
    ("high-to-low-cable-fly", "High-to-Low Cable Fly", "strength", "push", "isolation", "beginner", "", False, "lower_chest", "front_delts", "cable"),
    ("cable-crossover", "Cable Crossover", "strength", "push", "isolation", "intermediate", "", False, "mid_chest", "front_delts", "cable"),
    ("pec-deck", "Pec Deck", "strength", "push", "isolation", "beginner", "", False, "mid_chest", "front_delts", "machine"),
    ("machine-chest-press", "Machine Chest Press", "strength", "push", "compound", "beginner", "", False, "mid_chest", "triceps|front_delts", "machine"),
    ("incline-machine-press", "Incline Machine Press", "strength", "push", "compound", "beginner", "", False, "upper_chest", "triceps|front_delts", "machine"),
    ("smith-machine-bench-press", "Smith Machine Bench Press", "strength", "push", "compound", "beginner", "", False, "mid_chest", "triceps|front_delts", "smith_machine|bench"),
    ("push-up", "Push-Up", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "mid_chest", "triceps|front_delts|abs", "bodyweight"),
    ("incline-push-up", "Incline Push-Up", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "lower_chest", "triceps|front_delts", "bodyweight|bench"),
    ("decline-push-up", "Decline Push-Up", "strength", "push", "compound", "intermediate", "bodyweight_reps", False, "upper_chest", "triceps|front_delts", "bodyweight|box"),
    ("diamond-push-up", "Diamond Push-Up", "strength", "push", "compound", "intermediate", "bodyweight_reps", False, "triceps", "mid_chest", "bodyweight"),
    ("wide-grip-push-up", "Wide-Grip Push-Up", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "mid_chest", "front_delts", "bodyweight"),
    ("weighted-push-up", "Weighted Push-Up", "strength", "push", "compound", "advanced", "weighted_bodyweight", False, "mid_chest", "triceps|front_delts", "bodyweight|plate"),
    ("chest-dip", "Chest Dip", "strength", "push", "compound", "intermediate", "bodyweight_reps", False, "lower_chest", "triceps|front_delts", "dip_bars"),
    ("weighted-chest-dip", "Weighted Chest Dip", "strength", "push", "compound", "advanced", "weighted_bodyweight", False, "lower_chest", "triceps|front_delts", "dip_bars|plate"),
    ("dumbbell-pullover", "Dumbbell Pullover", "strength", "pull", "compound", "intermediate", "", False, "mid_chest|lats", "triceps", "dumbbell|bench"),
    ("svend-press", "Svend Press", "strength", "push", "isolation", "beginner", "", False, "mid_chest", "front_delts", "plate"),
    ("landmine-press", "Landmine Press", "strength", "push", "compound", "intermediate", "", True, "upper_chest|front_delts", "triceps", "landmine|barbell"),
    ("floor-press", "Floor Press", "strength", "push", "compound", "intermediate", "", False, "mid_chest|triceps", "front_delts", "barbell"),
    ("resistance-band-chest-press", "Resistance Band Chest Press", "strength", "push", "compound", "beginner", "", False, "mid_chest", "triceps|front_delts", "resistance_band"),

    # -------------------------------------------------------------------- back
    ("deadlift", "Deadlift", "powerlifting", "pull", "compound", "advanced", "", False, "lower_back|glutes|hamstrings", "lats|traps|forearms|quads", "barbell"),
    ("sumo-deadlift", "Sumo Deadlift", "powerlifting", "pull", "compound", "advanced", "", False, "glutes|quads|lower_back", "hamstrings|traps|adductors", "barbell"),
    ("romanian-deadlift", "Romanian Deadlift", "strength", "pull", "compound", "intermediate", "", False, "hamstrings|glutes", "lower_back|forearms", "barbell"),
    ("stiff-leg-deadlift", "Stiff-Leg Deadlift", "strength", "pull", "compound", "intermediate", "", False, "hamstrings", "glutes|lower_back", "barbell"),
    ("trap-bar-deadlift", "Trap Bar Deadlift", "strength", "pull", "compound", "beginner", "", False, "quads|glutes|lower_back", "traps|forearms", "trap_bar"),
    ("deficit-deadlift", "Deficit Deadlift", "powerlifting", "pull", "compound", "advanced", "", False, "lower_back|hamstrings|glutes", "quads|traps", "barbell|plate"),
    ("rack-pull", "Rack Pull", "powerlifting", "pull", "compound", "intermediate", "", False, "traps|lower_back", "lats|forearms|glutes", "barbell|squat_rack"),
    ("dumbbell-romanian-deadlift", "Dumbbell Romanian Deadlift", "strength", "pull", "compound", "beginner", "", False, "hamstrings|glutes", "lower_back", "dumbbell"),
    ("pull-up", "Pull-Up", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "lats", "biceps|rhomboids|teres_major", "pull_up_bar"),
    ("weighted-pull-up", "Weighted Pull-Up", "strength", "pull", "compound", "advanced", "weighted_bodyweight", False, "lats", "biceps|rhomboids", "pull_up_bar|plate"),
    ("chin-up", "Chin-Up", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "lats|biceps", "rhomboids", "pull_up_bar"),
    ("weighted-chin-up", "Weighted Chin-Up", "strength", "pull", "compound", "advanced", "weighted_bodyweight", False, "lats|biceps", "rhomboids", "pull_up_bar|plate"),
    ("neutral-grip-pull-up", "Neutral-Grip Pull-Up", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "lats", "biceps|brachialis", "pull_up_bar"),
    ("wide-grip-pull-up", "Wide-Grip Pull-Up", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "lats|teres_major", "rhomboids|biceps", "pull_up_bar"),
    ("assisted-pull-up", "Assisted Pull-Up", "strength", "pull", "compound", "beginner", "", False, "lats", "biceps|rhomboids", "machine"),
    ("lat-pulldown", "Lat Pulldown", "strength", "pull", "compound", "beginner", "", False, "lats", "biceps|rhomboids", "cable"),
    ("close-grip-lat-pulldown", "Close-Grip Lat Pulldown", "strength", "pull", "compound", "beginner", "", False, "lats", "biceps|brachialis", "cable"),
    ("wide-grip-lat-pulldown", "Wide-Grip Lat Pulldown", "strength", "pull", "compound", "beginner", "", False, "lats|teres_major", "biceps", "cable"),
    ("reverse-grip-lat-pulldown", "Reverse-Grip Lat Pulldown", "strength", "pull", "compound", "beginner", "", False, "lats|biceps", "rhomboids", "cable"),
    ("straight-arm-pulldown", "Straight-Arm Pulldown", "strength", "pull", "isolation", "beginner", "", False, "lats", "triceps", "cable"),
    ("barbell-row", "Barbell Row", "strength", "pull", "compound", "intermediate", "", False, "lats|rhomboids", "biceps|rear_delts|lower_back", "barbell"),
    ("pendlay-row", "Pendlay Row", "strength", "pull", "compound", "advanced", "", False, "lats|rhomboids", "biceps|traps", "barbell"),
    ("yates-row", "Yates Row", "strength", "pull", "compound", "intermediate", "", False, "lats|traps", "biceps|rear_delts", "barbell"),
    ("t-bar-row", "T-Bar Row", "strength", "pull", "compound", "intermediate", "", False, "lats|rhomboids", "biceps|rear_delts", "landmine|barbell"),
    ("dumbbell-row", "Dumbbell Row", "strength", "pull", "compound", "beginner", "", True, "lats", "biceps|rhomboids|rear_delts", "dumbbell|bench"),
    ("chest-supported-dumbbell-row", "Chest-Supported Dumbbell Row", "strength", "pull", "compound", "beginner", "", False, "rhomboids|lats", "rear_delts|biceps", "dumbbell|incline_bench"),
    ("seated-cable-row", "Seated Cable Row", "strength", "pull", "compound", "beginner", "", False, "rhomboids|lats", "biceps|rear_delts", "cable"),
    ("wide-grip-seated-row", "Wide-Grip Seated Row", "strength", "pull", "compound", "beginner", "", False, "rhomboids|rear_delts", "lats|biceps", "cable"),
    ("single-arm-cable-row", "Single-Arm Cable Row", "strength", "pull", "compound", "beginner", "", True, "lats", "biceps|rhomboids", "cable"),
    ("machine-row", "Machine Row", "strength", "pull", "compound", "beginner", "", False, "rhomboids|lats", "biceps|rear_delts", "machine"),
    ("inverted-row", "Inverted Row", "strength", "pull", "compound", "beginner", "bodyweight_reps", False, "rhomboids|lats", "biceps|rear_delts", "barbell|squat_rack"),
    ("trx-row", "TRX Row", "strength", "pull", "compound", "beginner", "bodyweight_reps", False, "rhomboids|lats", "biceps|rear_delts", "trx"),
    ("meadows-row", "Meadows Row", "strength", "pull", "compound", "advanced", "", True, "lats|rhomboids", "biceps|rear_delts", "landmine|barbell"),
    ("seal-row", "Seal Row", "strength", "pull", "compound", "intermediate", "", False, "rhomboids|lats", "rear_delts|biceps", "barbell|bench"),
    ("kroc-row", "Kroc Row", "strength", "pull", "compound", "advanced", "", True, "lats|traps", "biceps|forearms", "dumbbell|bench"),
    ("back-extension", "Back Extension", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "lower_back|erectors", "glutes|hamstrings", "machine"),
    ("weighted-back-extension", "Weighted Back Extension", "strength", "pull", "isolation", "intermediate", "weighted_bodyweight", False, "lower_back|erectors", "glutes|hamstrings", "machine|plate"),
    ("good-morning", "Good Morning", "strength", "pull", "compound", "advanced", "", False, "hamstrings|lower_back", "glutes|erectors", "barbell"),
    ("barbell-shrug", "Barbell Shrug", "strength", "pull", "isolation", "beginner", "", False, "traps", "forearms", "barbell"),
    ("dumbbell-shrug", "Dumbbell Shrug", "strength", "pull", "isolation", "beginner", "", False, "traps", "forearms", "dumbbell"),
    ("trap-bar-shrug", "Trap Bar Shrug", "strength", "pull", "isolation", "beginner", "", False, "traps", "forearms", "trap_bar"),
    ("cable-shrug", "Cable Shrug", "strength", "pull", "isolation", "beginner", "", False, "traps", "forearms", "cable"),

    # --------------------------------------------------------------- shoulders
    ("overhead-press", "Overhead Press", "strength", "push", "compound", "intermediate", "", False, "front_delts", "triceps|side_delts|abs", "barbell"),
    ("push-press", "Push Press", "olympic", "push", "compound", "advanced", "", False, "front_delts", "triceps|quads|glutes", "barbell"),
    ("seated-barbell-press", "Seated Barbell Overhead Press", "strength", "push", "compound", "intermediate", "", False, "front_delts", "triceps|side_delts", "barbell|bench"),
    ("behind-the-neck-press", "Behind-the-Neck Press", "strength", "push", "compound", "advanced", "", False, "side_delts|front_delts", "triceps", "barbell|bench"),
    ("dumbbell-shoulder-press", "Dumbbell Shoulder Press", "strength", "push", "compound", "beginner", "", False, "front_delts", "triceps|side_delts", "dumbbell|bench"),
    ("seated-dumbbell-press", "Seated Dumbbell Shoulder Press", "strength", "push", "compound", "beginner", "", False, "front_delts", "triceps|side_delts", "dumbbell|bench"),
    ("arnold-press", "Arnold Press", "strength", "push", "compound", "intermediate", "", False, "front_delts|side_delts", "triceps", "dumbbell|bench"),
    ("machine-shoulder-press", "Machine Shoulder Press", "strength", "push", "compound", "beginner", "", False, "front_delts", "triceps|side_delts", "machine"),
    ("smith-machine-shoulder-press", "Smith Machine Shoulder Press", "strength", "push", "compound", "beginner", "", False, "front_delts", "triceps", "smith_machine|bench"),
    ("lateral-raise", "Lateral Raise", "strength", "push", "isolation", "beginner", "", False, "side_delts", "traps", "dumbbell"),
    ("cable-lateral-raise", "Cable Lateral Raise", "strength", "push", "isolation", "beginner", "", True, "side_delts", "traps", "cable"),
    ("machine-lateral-raise", "Machine Lateral Raise", "strength", "push", "isolation", "beginner", "", False, "side_delts", "traps", "machine"),
    ("leaning-lateral-raise", "Leaning Lateral Raise", "strength", "push", "isolation", "intermediate", "", True, "side_delts", "traps", "dumbbell"),
    ("front-raise", "Front Raise", "strength", "push", "isolation", "beginner", "", False, "front_delts", "upper_chest", "dumbbell"),
    ("cable-front-raise", "Cable Front Raise", "strength", "push", "isolation", "beginner", "", False, "front_delts", "upper_chest", "cable"),
    ("plate-front-raise", "Plate Front Raise", "strength", "push", "isolation", "beginner", "", False, "front_delts", "upper_chest", "plate"),
    ("rear-delt-fly", "Rear Delt Fly", "strength", "pull", "isolation", "beginner", "", False, "rear_delts", "rhomboids|traps", "dumbbell"),
    ("reverse-pec-deck", "Reverse Pec Deck", "strength", "pull", "isolation", "beginner", "", False, "rear_delts", "rhomboids", "machine"),
    ("cable-rear-delt-fly", "Cable Rear Delt Fly", "strength", "pull", "isolation", "beginner", "", False, "rear_delts", "rhomboids", "cable"),
    ("face-pull", "Face Pull", "strength", "pull", "compound", "beginner", "", False, "rear_delts", "rhomboids|rotator_cuff|traps", "cable"),
    ("upright-row", "Upright Row", "strength", "pull", "compound", "intermediate", "", False, "side_delts|traps", "biceps", "barbell"),
    ("cable-upright-row", "Cable Upright Row", "strength", "pull", "compound", "beginner", "", False, "side_delts|traps", "biceps", "cable"),
    ("handstand-push-up", "Handstand Push-Up", "strength", "push", "compound", "advanced", "bodyweight_reps", False, "front_delts", "triceps|traps", "bodyweight"),
    ("pike-push-up", "Pike Push-Up", "strength", "push", "compound", "intermediate", "bodyweight_reps", False, "front_delts", "triceps|upper_chest", "bodyweight"),
    ("external-rotation", "Cable External Rotation", "mobility", "pull", "isolation", "beginner", "", True, "rotator_cuff", "rear_delts", "cable"),
    ("band-pull-apart", "Band Pull-Apart", "strength", "pull", "isolation", "beginner", "", False, "rear_delts", "rhomboids|traps", "resistance_band"),
    ("landmine-lateral-raise", "Landmine Lateral Raise", "strength", "push", "isolation", "intermediate", "", True, "side_delts", "front_delts", "landmine|barbell"),

    # -------------------------------------------------------------------- arms
    ("barbell-curl", "Barbell Curl", "strength", "pull", "isolation", "beginner", "", False, "biceps", "forearms|brachialis", "barbell"),
    ("ez-bar-curl", "EZ Bar Curl", "strength", "pull", "isolation", "beginner", "", False, "biceps", "forearms|brachialis", "ez_bar"),
    ("dumbbell-curl", "Dumbbell Curl", "strength", "pull", "isolation", "beginner", "", False, "biceps", "forearms|brachialis", "dumbbell"),
    ("alternating-dumbbell-curl", "Alternating Dumbbell Curl", "strength", "pull", "isolation", "beginner", "", True, "biceps", "forearms", "dumbbell"),
    ("hammer-curl", "Hammer Curl", "strength", "pull", "isolation", "beginner", "", False, "brachialis|biceps", "forearms", "dumbbell"),
    ("cross-body-hammer-curl", "Cross-Body Hammer Curl", "strength", "pull", "isolation", "beginner", "", True, "brachialis", "biceps|forearms", "dumbbell"),
    ("preacher-curl", "Preacher Curl", "strength", "pull", "isolation", "intermediate", "", False, "biceps", "brachialis", "ez_bar|bench"),
    ("dumbbell-preacher-curl", "Dumbbell Preacher Curl", "strength", "pull", "isolation", "intermediate", "", True, "biceps", "brachialis", "dumbbell|bench"),
    ("incline-dumbbell-curl", "Incline Dumbbell Curl", "strength", "pull", "isolation", "intermediate", "", False, "biceps", "brachialis", "dumbbell|incline_bench"),
    ("concentration-curl", "Concentration Curl", "strength", "pull", "isolation", "beginner", "", True, "biceps", "brachialis", "dumbbell|bench"),
    ("cable-curl", "Cable Curl", "strength", "pull", "isolation", "beginner", "", False, "biceps", "forearms", "cable"),
    ("cable-hammer-curl", "Cable Hammer Curl", "strength", "pull", "isolation", "beginner", "", False, "brachialis|biceps", "forearms", "cable"),
    ("spider-curl", "Spider Curl", "strength", "pull", "isolation", "intermediate", "", False, "biceps", "brachialis", "dumbbell|incline_bench"),
    ("machine-curl", "Machine Curl", "strength", "pull", "isolation", "beginner", "", False, "biceps", "brachialis", "machine"),
    ("reverse-curl", "Reverse Curl", "strength", "pull", "isolation", "beginner", "", False, "forearms|brachialis", "biceps", "ez_bar"),
    ("zottman-curl", "Zottman Curl", "strength", "pull", "isolation", "intermediate", "", False, "biceps|forearms", "brachialis", "dumbbell"),
    ("21s-bicep-curl", "21s Bicep Curl", "strength", "pull", "isolation", "intermediate", "", False, "biceps", "forearms", "barbell"),
    ("tricep-pushdown", "Tricep Pushdown", "strength", "push", "isolation", "beginner", "", False, "triceps", "", "cable"),
    ("rope-pushdown", "Rope Tricep Pushdown", "strength", "push", "isolation", "beginner", "", False, "triceps", "", "cable"),
    ("reverse-grip-pushdown", "Reverse-Grip Pushdown", "strength", "push", "isolation", "beginner", "", False, "triceps", "", "cable"),
    ("skull-crusher", "Skull Crusher", "strength", "push", "isolation", "intermediate", "", False, "triceps", "", "ez_bar|bench"),
    ("dumbbell-skull-crusher", "Dumbbell Skull Crusher", "strength", "push", "isolation", "intermediate", "", False, "triceps", "", "dumbbell|bench"),
    ("overhead-tricep-extension", "Overhead Tricep Extension", "strength", "push", "isolation", "beginner", "", False, "triceps", "", "dumbbell"),
    ("cable-overhead-extension", "Cable Overhead Tricep Extension", "strength", "push", "isolation", "beginner", "", False, "triceps", "", "cable"),
    ("tricep-kickback", "Tricep Kickback", "strength", "push", "isolation", "beginner", "", True, "triceps", "", "dumbbell"),
    ("cable-tricep-kickback", "Cable Tricep Kickback", "strength", "push", "isolation", "beginner", "", True, "triceps", "", "cable"),
    ("tricep-dip", "Tricep Dip", "strength", "push", "compound", "intermediate", "bodyweight_reps", False, "triceps", "lower_chest|front_delts", "dip_bars"),
    ("bench-dip", "Bench Dip", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "triceps", "front_delts", "bench"),
    ("jm-press", "JM Press", "strength", "push", "compound", "advanced", "", False, "triceps", "mid_chest", "barbell|bench"),
    ("wrist-curl", "Wrist Curl", "strength", "pull", "isolation", "beginner", "", False, "forearms", "", "dumbbell|bench"),
    ("reverse-wrist-curl", "Reverse Wrist Curl", "strength", "pull", "isolation", "beginner", "", False, "forearms", "", "dumbbell|bench"),
    ("farmers-walk", "Farmer's Walk", "strongman", "static", "compound", "intermediate", "distance_time", False, "forearms|traps", "abs|glutes", "dumbbell"),
    ("dead-hang", "Dead Hang", "strength", "static", "isolation", "beginner", "time", False, "forearms", "lats", "pull_up_bar"),
    ("plate-pinch", "Plate Pinch Hold", "strongman", "static", "isolation", "intermediate", "time", False, "forearms", "", "plate"),

    # -------------------------------------------------------------------- legs
    ("back-squat", "Back Squat", "powerlifting", "push", "compound", "intermediate", "", False, "quads|glutes", "hamstrings|erectors|abs", "barbell|squat_rack"),
    ("front-squat", "Front Squat", "olympic", "push", "compound", "advanced", "", False, "quads", "glutes|abs|erectors", "barbell|squat_rack"),
    ("high-bar-squat", "High-Bar Squat", "strength", "push", "compound", "intermediate", "", False, "quads", "glutes|hamstrings", "barbell|squat_rack"),
    ("low-bar-squat", "Low-Bar Squat", "powerlifting", "push", "compound", "advanced", "", False, "glutes|quads", "hamstrings|lower_back", "barbell|squat_rack"),
    ("box-squat", "Box Squat", "powerlifting", "push", "compound", "intermediate", "", False, "glutes|quads", "hamstrings", "barbell|box"),
    ("pause-squat", "Pause Squat", "powerlifting", "push", "compound", "advanced", "", False, "quads|glutes", "hamstrings|abs", "barbell|squat_rack"),
    ("goblet-squat", "Goblet Squat", "strength", "push", "compound", "beginner", "", False, "quads|glutes", "abs", "dumbbell"),
    ("dumbbell-squat", "Dumbbell Squat", "strength", "push", "compound", "beginner", "", False, "quads|glutes", "hamstrings", "dumbbell"),
    ("smith-machine-squat", "Smith Machine Squat", "strength", "push", "compound", "beginner", "", False, "quads|glutes", "hamstrings", "smith_machine"),
    ("hack-squat", "Hack Squat", "strength", "push", "compound", "intermediate", "", False, "quads", "glutes", "machine"),
    ("leg-press", "Leg Press", "strength", "push", "compound", "beginner", "", False, "quads|glutes", "hamstrings", "leg_press"),
    ("single-leg-press", "Single-Leg Press", "strength", "push", "compound", "intermediate", "", True, "quads|glutes", "hamstrings", "leg_press"),
    ("bulgarian-split-squat", "Bulgarian Split Squat", "strength", "push", "compound", "intermediate", "", True, "quads|glutes", "hamstrings|adductors", "dumbbell|bench"),
    ("split-squat", "Split Squat", "strength", "push", "compound", "beginner", "", True, "quads|glutes", "hamstrings", "dumbbell"),
    ("walking-lunge", "Walking Lunge", "strength", "push", "compound", "beginner", "", True, "quads|glutes", "hamstrings|adductors", "dumbbell"),
    ("reverse-lunge", "Reverse Lunge", "strength", "push", "compound", "beginner", "", True, "glutes|quads", "hamstrings", "dumbbell"),
    ("barbell-lunge", "Barbell Lunge", "strength", "push", "compound", "intermediate", "", True, "quads|glutes", "hamstrings", "barbell"),
    ("curtsy-lunge", "Curtsy Lunge", "strength", "push", "compound", "intermediate", "", True, "glutes|abductors", "quads", "dumbbell"),
    ("step-up", "Step-Up", "strength", "push", "compound", "beginner", "", True, "quads|glutes", "hamstrings|calves", "dumbbell|box"),
    ("pistol-squat", "Pistol Squat", "strength", "push", "compound", "advanced", "bodyweight_reps", True, "quads|glutes", "abs|hamstrings", "bodyweight"),
    ("bodyweight-squat", "Bodyweight Squat", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "quads|glutes", "hamstrings", "bodyweight"),
    ("sissy-squat", "Sissy Squat", "strength", "push", "isolation", "advanced", "bodyweight_reps", False, "quads", "hip_flexors", "bodyweight"),
    ("zercher-squat", "Zercher Squat", "strongman", "push", "compound", "advanced", "", False, "quads|glutes", "abs|erectors", "barbell"),
    ("leg-extension", "Leg Extension", "strength", "push", "isolation", "beginner", "", False, "quads", "", "machine"),
    ("single-leg-extension", "Single-Leg Extension", "strength", "push", "isolation", "beginner", "", True, "quads", "", "machine"),
    ("lying-leg-curl", "Lying Leg Curl", "strength", "pull", "isolation", "beginner", "", False, "hamstrings", "calves", "machine"),
    ("seated-leg-curl", "Seated Leg Curl", "strength", "pull", "isolation", "beginner", "", False, "hamstrings", "calves", "machine"),
    ("standing-leg-curl", "Standing Leg Curl", "strength", "pull", "isolation", "beginner", "", True, "hamstrings", "", "machine"),
    ("nordic-curl", "Nordic Hamstring Curl", "strength", "pull", "isolation", "advanced", "bodyweight_reps", False, "hamstrings", "glutes|calves", "bodyweight"),
    ("glute-ham-raise", "Glute-Ham Raise", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "hamstrings|glutes", "erectors", "machine"),
    ("hip-thrust", "Barbell Hip Thrust", "strength", "push", "compound", "intermediate", "", False, "glutes", "hamstrings|quads", "barbell|bench"),
    ("dumbbell-hip-thrust", "Dumbbell Hip Thrust", "strength", "push", "compound", "beginner", "", False, "glutes", "hamstrings", "dumbbell|bench"),
    ("machine-hip-thrust", "Machine Hip Thrust", "strength", "push", "compound", "beginner", "", False, "glutes", "hamstrings", "machine"),
    ("glute-bridge", "Glute Bridge", "strength", "push", "compound", "beginner", "bodyweight_reps", False, "glutes", "hamstrings", "bodyweight"),
    ("single-leg-glute-bridge", "Single-Leg Glute Bridge", "strength", "push", "compound", "intermediate", "bodyweight_reps", True, "glutes", "hamstrings|abs", "bodyweight"),
    ("cable-glute-kickback", "Cable Glute Kickback", "strength", "push", "isolation", "beginner", "", True, "glutes", "hamstrings", "cable"),
    ("hip-abduction", "Hip Abduction", "strength", "push", "isolation", "beginner", "", False, "abductors", "glutes", "machine"),
    ("hip-adduction", "Hip Adduction", "strength", "pull", "isolation", "beginner", "", False, "adductors", "", "machine"),
    ("standing-calf-raise", "Standing Calf Raise", "strength", "push", "isolation", "beginner", "", False, "calves", "", "machine"),
    ("seated-calf-raise", "Seated Calf Raise", "strength", "push", "isolation", "beginner", "", False, "calves", "", "machine"),
    ("smith-machine-calf-raise", "Smith Machine Calf Raise", "strength", "push", "isolation", "beginner", "", False, "calves", "", "smith_machine"),
    ("leg-press-calf-raise", "Leg Press Calf Raise", "strength", "push", "isolation", "beginner", "", False, "calves", "", "leg_press"),
    ("single-leg-calf-raise", "Single-Leg Calf Raise", "strength", "push", "isolation", "beginner", "", True, "calves", "", "dumbbell"),
    ("donkey-calf-raise", "Donkey Calf Raise", "strength", "push", "isolation", "intermediate", "", False, "calves", "", "machine"),

    # -------------------------------------------------------------------- core
    ("plank", "Plank", "strength", "static", "isolation", "beginner", "time", False, "abs|transverse_abs", "obliques|erectors", "bodyweight"),
    ("side-plank", "Side Plank", "strength", "static", "isolation", "beginner", "time", True, "obliques", "abs|transverse_abs", "bodyweight"),
    ("weighted-plank", "Weighted Plank", "strength", "static", "isolation", "intermediate", "time", False, "abs|transverse_abs", "obliques", "bodyweight|plate"),
    ("crunch", "Crunch", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "abs", "obliques", "bodyweight"),
    ("cable-crunch", "Cable Crunch", "strength", "pull", "isolation", "beginner", "", False, "abs", "obliques", "cable"),
    ("machine-crunch", "Machine Crunch", "strength", "pull", "isolation", "beginner", "", False, "abs", "obliques", "machine"),
    ("bicycle-crunch", "Bicycle Crunch", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "obliques|abs", "hip_flexors", "bodyweight"),
    ("sit-up", "Sit-Up", "strength", "pull", "compound", "beginner", "bodyweight_reps", False, "abs", "hip_flexors|obliques", "bodyweight"),
    ("decline-sit-up", "Decline Sit-Up", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "abs", "hip_flexors", "bench"),
    ("hanging-leg-raise", "Hanging Leg Raise", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "abs|hip_flexors", "obliques|forearms", "pull_up_bar"),
    ("hanging-knee-raise", "Hanging Knee Raise", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "abs|hip_flexors", "forearms", "pull_up_bar"),
    ("captains-chair-leg-raise", "Captain's Chair Leg Raise", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "abs|hip_flexors", "obliques", "machine"),
    ("lying-leg-raise", "Lying Leg Raise", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "abs|hip_flexors", "", "bodyweight"),
    ("flutter-kick", "Flutter Kick", "strength", "pull", "isolation", "beginner", "time", False, "abs|hip_flexors", "", "bodyweight"),
    ("russian-twist", "Russian Twist", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "obliques", "abs", "medicine_ball"),
    ("wood-chop", "Cable Wood Chop", "strength", "pull", "compound", "intermediate", "", True, "obliques", "abs|front_delts", "cable"),
    ("pallof-press", "Pallof Press", "strength", "static", "isolation", "intermediate", "", True, "obliques|transverse_abs", "abs", "cable"),
    ("ab-wheel-rollout", "Ab Wheel Rollout", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "abs|transverse_abs", "lats|erectors", "ab_wheel"),
    ("barbell-rollout", "Barbell Rollout", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "abs|transverse_abs", "lats", "barbell"),
    ("dead-bug", "Dead Bug", "mobility", "static", "isolation", "beginner", "bodyweight_reps", False, "transverse_abs|abs", "hip_flexors", "bodyweight"),
    ("bird-dog", "Bird Dog", "mobility", "static", "isolation", "beginner", "bodyweight_reps", True, "erectors|transverse_abs", "glutes", "bodyweight"),
    ("hollow-body-hold", "Hollow Body Hold", "strength", "static", "isolation", "intermediate", "time", False, "abs|transverse_abs", "hip_flexors", "bodyweight"),
    ("mountain-climber", "Mountain Climber", "cardio", "push", "compound", "beginner", "time", False, "abs", "hip_flexors|front_delts", "bodyweight"),
    ("dragon-flag", "Dragon Flag", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "abs|transverse_abs", "erectors|lats", "bench"),
    ("side-bend", "Dumbbell Side Bend", "strength", "pull", "isolation", "beginner", "", True, "obliques", "erectors", "dumbbell"),
    ("stability-ball-crunch", "Stability Ball Crunch", "strength", "pull", "isolation", "beginner", "bodyweight_reps", False, "abs", "obliques", "stability_ball"),
    ("stability-ball-hamstring-curl", "Stability Ball Hamstring Curl", "strength", "pull", "compound", "intermediate", "bodyweight_reps", False, "hamstrings", "glutes|abs", "stability_ball"),
    ("stability-ball-pike", "Stability Ball Pike", "strength", "pull", "compound", "advanced", "bodyweight_reps", False, "abs|transverse_abs", "front_delts|hip_flexors", "stability_ball"),
    ("stability-ball-plank", "Stability Ball Plank", "strength", "static", "isolation", "intermediate", "time", False, "abs|transverse_abs", "obliques|front_delts", "stability_ball"),

    # ---------------------------------------------------------- olympic & power
    ("clean-and-jerk", "Clean and Jerk", "olympic", "pull", "compound", "advanced", "", False, "quads|glutes|traps", "front_delts|hamstrings|erectors", "barbell"),
    ("power-clean", "Power Clean", "olympic", "pull", "compound", "advanced", "", False, "quads|glutes|traps", "hamstrings|erectors|forearms", "barbell"),
    ("hang-clean", "Hang Clean", "olympic", "pull", "compound", "advanced", "", False, "traps|glutes", "quads|hamstrings", "barbell"),
    ("snatch", "Snatch", "olympic", "pull", "compound", "advanced", "", False, "quads|glutes|traps", "front_delts|hamstrings|erectors", "barbell"),
    ("power-snatch", "Power Snatch", "olympic", "pull", "compound", "advanced", "", False, "traps|glutes|quads", "front_delts|hamstrings", "barbell"),
    ("hang-snatch", "Hang Snatch", "olympic", "pull", "compound", "advanced", "", False, "traps|glutes", "quads|front_delts", "barbell"),
    ("clean-pull", "Clean Pull", "olympic", "pull", "compound", "advanced", "", False, "traps|glutes|hamstrings", "erectors|forearms", "barbell"),
    ("snatch-grip-deadlift", "Snatch-Grip Deadlift", "olympic", "pull", "compound", "advanced", "", False, "hamstrings|lower_back|traps", "glutes|forearms", "barbell"),
    ("thruster", "Thruster", "olympic", "push", "compound", "advanced", "", False, "quads|front_delts", "glutes|triceps", "barbell"),
    ("jerk", "Split Jerk", "olympic", "push", "compound", "advanced", "", False, "front_delts|quads", "triceps|glutes", "barbell"),
    ("kettlebell-swing", "Kettlebell Swing", "strength", "pull", "compound", "intermediate", "", False, "glutes|hamstrings", "erectors|abs", "kettlebell"),
    ("kettlebell-clean", "Kettlebell Clean", "strength", "pull", "compound", "intermediate", "", True, "glutes|traps", "hamstrings|forearms", "kettlebell"),
    ("kettlebell-snatch", "Kettlebell Snatch", "strength", "pull", "compound", "advanced", "", True, "glutes|traps", "front_delts|hamstrings", "kettlebell"),
    ("turkish-get-up", "Turkish Get-Up", "strength", "push", "compound", "advanced", "", True, "abs|front_delts", "glutes|quads|obliques", "kettlebell"),
    ("kettlebell-goblet-squat", "Kettlebell Goblet Squat", "strength", "push", "compound", "beginner", "", False, "quads|glutes", "abs", "kettlebell"),

    # ------------------------------------------------------------- plyometrics
    ("box-jump", "Box Jump", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|glutes", "calves|hamstrings", "box"),
    ("broad-jump", "Broad Jump", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|glutes", "calves|hamstrings", "bodyweight"),
    ("jump-squat", "Jump Squat", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|glutes", "calves", "bodyweight"),
    ("burpee", "Burpee", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|mid_chest", "abs|front_delts|triceps", "bodyweight"),
    ("jumping-lunge", "Jumping Lunge", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", True, "quads|glutes", "calves", "bodyweight"),
    ("depth-jump", "Depth Jump", "plyometrics", "push", "compound", "advanced", "bodyweight_reps", False, "quads|calves", "glutes", "box"),
    ("clap-push-up", "Clap Push-Up", "plyometrics", "push", "compound", "advanced", "bodyweight_reps", False, "mid_chest|triceps", "front_delts", "bodyweight"),
    ("medicine-ball-slam", "Medicine Ball Slam", "plyometrics", "push", "compound", "beginner", "bodyweight_reps", False, "abs|lats", "front_delts|quads", "medicine_ball"),
    ("wall-ball", "Wall Ball", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|front_delts", "glutes|abs", "medicine_ball"),
    ("tuck-jump", "Tuck Jump", "plyometrics", "push", "compound", "intermediate", "bodyweight_reps", False, "quads|hip_flexors", "calves|abs", "bodyweight"),

    # ------------------------------------------------------------------ cardio
    ("treadmill-run", "Treadmill Run", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "quads|calves|hamstrings", "treadmill"),
    ("outdoor-run", "Outdoor Run", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "quads|calves|hamstrings", "none"),
    ("treadmill-walk", "Treadmill Walk", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "quads|calves", "treadmill"),
    ("incline-walk", "Incline Treadmill Walk", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "glutes|calves|quads", "treadmill"),
    ("stationary-bike", "Stationary Bike", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "quads|calves", "bike"),
    ("spin-bike", "Spin Bike", "cardio", "", "compound", "intermediate", "distance_time", False, "cardiovascular", "quads|glutes", "bike"),
    ("rowing-machine", "Rowing Machine", "cardio", "pull", "compound", "beginner", "distance_time", False, "cardiovascular", "lats|quads|rhomboids", "rower"),
    ("elliptical", "Elliptical", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "quads|glutes", "elliptical"),
    ("stair-climber", "Stair Climber", "cardio", "", "compound", "beginner", "distance_time", False, "cardiovascular", "glutes|quads|calves", "stair_climber"),
    ("jump-rope", "Jump Rope", "cardio", "", "compound", "beginner", "time", False, "cardiovascular", "calves|forearms", "jump_rope"),
    ("battle-ropes", "Battle Ropes", "cardio", "pull", "compound", "intermediate", "time", False, "cardiovascular", "front_delts|abs|forearms", "none"),
    ("sled-push", "Sled Push", "strongman", "push", "compound", "intermediate", "distance_time", False, "quads|glutes", "calves|abs", "sled"),
    ("sled-pull", "Sled Pull", "strongman", "pull", "compound", "intermediate", "distance_time", False, "hamstrings|glutes", "lats|forearms", "sled"),
    ("assault-bike", "Assault Bike", "cardio", "", "compound", "intermediate", "distance_time", False, "cardiovascular", "quads|front_delts", "bike"),
    ("swimming", "Swimming", "cardio", "", "compound", "intermediate", "distance_time", False, "cardiovascular", "lats|front_delts|quads", "none"),
    ("stationary-bike-intervals", "Bike Intervals", "cardio", "", "compound", "advanced", "time", False, "cardiovascular", "quads|glutes", "bike"),

    # ------------------------------------------------- stretching  &  mobility
    ("hamstring-stretch", "Hamstring Stretch", "stretching", "static", "isolation", "beginner", "time", True, "hamstrings", "", "none"),
    ("quad-stretch", "Quad Stretch", "stretching", "static", "isolation", "beginner", "time", True, "quads", "hip_flexors", "none"),
    ("hip-flexor-stretch", "Hip Flexor Stretch", "stretching", "static", "isolation", "beginner", "time", True, "hip_flexors", "quads", "none"),
    ("pigeon-pose", "Pigeon Pose", "stretching", "static", "isolation", "intermediate", "time", True, "glutes", "hip_flexors", "none"),
    ("childs-pose", "Child's Pose", "stretching", "static", "isolation", "beginner", "time", False, "lats|erectors", "", "none"),
    ("cat-cow", "Cat-Cow", "mobility", "static", "isolation", "beginner", "reps_only", False, "erectors", "abs", "none"),
    ("thoracic-rotation", "Thoracic Rotation", "mobility", "static", "isolation", "beginner", "reps_only", True, "erectors|obliques", "rear_delts", "none"),
    ("shoulder-dislocate", "Shoulder Dislocate", "mobility", "static", "isolation", "beginner", "reps_only", False, "rotator_cuff|front_delts", "traps", "resistance_band"),
    ("world-greatest-stretch", "World's Greatest Stretch", "mobility", "static", "compound", "intermediate", "reps_only", True, "hip_flexors|hamstrings", "obliques|glutes", "none"),
    ("couch-stretch", "Couch Stretch", "stretching", "static", "isolation", "intermediate", "time", True, "hip_flexors|quads", "", "none"),
    ("calf-stretch", "Calf Stretch", "stretching", "static", "isolation", "beginner", "time", True, "calves", "", "none"),
    ("chest-doorway-stretch", "Doorway Chest Stretch", "stretching", "static", "isolation", "beginner", "time", False, "mid_chest|front_delts", "", "none"),
    ("foam-roll-quads", "Foam Roll Quads", "mobility", "static", "isolation", "beginner", "time", False, "quads", "", "foam_roller"),
    ("foam-roll-back", "Foam Roll Upper Back", "mobility", "static", "isolation", "beginner", "time", False, "erectors|rhomboids", "", "foam_roller"),
    ("foam-roll-it-band", "Foam Roll IT Band", "mobility", "static", "isolation", "beginner", "time", True, "abductors", "quads", "foam_roller"),
    ("ninety-ninety-hip-stretch", "90/90 Hip Stretch", "mobility", "static", "isolation", "intermediate", "time", True, "glutes|hip_flexors", "adductors", "none"),
    ("neck-flexion", "Neck Flexion", "strength", "pull", "isolation", "beginner", "reps_only", False, "neck", "", "none"),
    ("neck-extension", "Neck Extension", "strength", "pull", "isolation", "beginner", "reps_only", False, "neck", "", "none"),

    # ---------------------------------------------------------- carries & misc
    ("suitcase-carry", "Suitcase Carry", "strongman", "static", "compound", "intermediate", "distance_time", True, "obliques|forearms", "traps|abs", "dumbbell"),
    ("overhead-carry", "Overhead Carry", "strongman", "static", "compound", "advanced", "distance_time", False, "front_delts|abs", "traps|triceps", "dumbbell"),
    ("front-rack-carry", "Front Rack Carry", "strongman", "static", "compound", "intermediate", "distance_time", False, "abs|traps", "front_delts|erectors", "kettlebell"),
    ("yoke-walk", "Yoke Walk", "strongman", "static", "compound", "advanced", "distance_time", False, "traps|erectors", "quads|abs", "none"),
    ("atlas-stone-lift", "Atlas Stone Lift", "strongman", "pull", "compound", "advanced", "", False, "lower_back|glutes", "lats|biceps|quads", "none"),
    ("tire-flip", "Tire Flip", "strongman", "push", "compound", "advanced", "reps_only", False, "quads|glutes|lats", "traps|biceps", "none"),
    ("log-press", "Log Press", "strongman", "push", "compound", "advanced", "", False, "front_delts|triceps", "quads|abs", "none"),
    ("bear-crawl", "Bear Crawl", "cardio", "push", "compound", "beginner", "distance_time", False, "abs|front_delts", "quads|triceps", "bodyweight"),
    ("crab-walk", "Crab Walk", "cardio", "push", "compound", "beginner", "distance_time", False, "triceps|glutes", "abs|front_delts", "bodyweight"),
)
# fmt: on
